export default LETTER_PRONUNCIATION = {
  Ⲁ: 'A as in Car',
  Ⲉ: 'E as in Let',
  Ⲍ: 'Z',
  Ⲏ: 'long EE as in Feet',
  Ⲓ: 'short I as in Fit & Y as in Yo',
  Ⲕ: 'K',
  Ⲙ: 'M',
  Ⲛ: 'N',
  Ⲝ: 'X',
  Ⲟ: 'Short O as in Fog',
  Ⲡ: 'P',
  Ⲣ: 'R',
  Ⲥ: 'S',
  Ⲧ: 'T',
  Ⲩ: 'y as in Hymn',
  Ⲫ: 'Ph',
  Ⲯ: 'Ps',
  Ⲱ: 'Long O as in Hope',
  Ϣ: 'Sh',
  Ϥ: 'F',
  Ϧ: 'Kh',
  Ϩ: 'H as in Hotel',
  Ϭ: 'Ch',
  Ϯ: 'Ti',
  ⲞⲨ: 'OO as in Food',
  '⳿': 'Ⲉ if on a consonant or a glottal stop before the vowel if on a vowel',
};
