export default LETTER_PRONUNCIATION = {
  Ⲁ: 'A as in Car',
  Ⲃ: 'V if followed by a vowel, B otherwise',
  Ⲅ: 'G if followed by ⲉ-ⲓ-ⲏ-ⲩ\nN if followed by ⲅ-ⲕ-ⲭ-ⲝ\nGH otherwise',
  Ⲇ: 'D in proper nouns, DH (in English: TH as in mother) otherwise',
  Ⲉ: 'E as in Let',
  Ⲍ: 'Z',
  Ⲏ: 'long EE as in Feet',
  Ⲑ: 'Th as in Theology, T if preceded by Ⲥ or Ϣ',
  Ⲓ: 'short I as in Fit & Y as in Yo',
  Ⲕ: 'K',
  Ⲙ: 'M',
  Ⲛ: 'N',
  Ⲝ: 'X',
  Ⲟ: 'Short O as in Fog',
  Ⲡ: 'P',
  Ⲣ: 'R',
  Ⲥ: 'S',
  Ⲧ: 'T',
  Ⲩ: 'y as in Hymn',
  ⲩ: 'V if preceded by ⲁ-ⲉ\nOO when combined with ⲟ\nY as in Hymn otherwise',
  Ⲫ: 'Ph',
  Ⲭ: 'Q in Coptic nouns\nSH when followed by ⲉ-ⲓ-ⲏ-ⲩ in Greek nouns\nKH otherwise in Greek nouns',
  Ⲯ: 'Ps',
  Ⲱ: 'Long O as in Hope',
  Ϣ: 'Sh',
  Ϥ: 'F',
  Ϧ: 'Kh',
  Ϩ: 'H as in Hotel',
  Ϭ: 'Ch',
  Ϯ: 'Ti',
  ⲞⲨ: 'OO as in Food',
  '⳿': 'Ⲉ if on a consonant or a glottal stop before the vowel if on a vowel',
};
